openapi: "3.0.0"
servers:
  - url: http://localhost:8080
info:
  version: 1.0.0
  title: Sample Blog API
  description: |
    A sample API that uses blog as an example.
  contact:
    name: Andriy Kornatskyy
    email: andriy.kornatskyy@live.com
  license:
    name: MIT
tags:
  - name: membership
    description: Everything about membership.
  - name: posts
    description: Everything about blog posts.
x-tagGroups:
  - name: General
    tags:
      - membership
  - name: Posts
    tags:
      - posts
paths:
  /signin:
    post:
      summary: Sign in user
      operationId: signIn
      tags:
        - membership
      requestBody:
        description: user credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'
        '400':
          description: validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorState'
  /signup:
    post:
      summary: Sign up user
      operationId: signUp
      tags:
        - membership
      requestBody:
        description: user registration information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResponse'
        '400':
          description: validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorState'
components:
  schemas:
    ErrorState:
      required:
        - errors
      properties:
        errors:
          additionalProperties:
            type: array
            items:
              type: string
      example:
        errors:
          username:
            - Required field cannot be left blank.
    SignInRequest:
      properties:
        username:
          type: string
          minLength: 2
          maxLength: 20
          example: demo
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 12
          example: password
      required:
        - username
        - password
    SignInResponse:
      properties:
        username:
          type: string
          example: demo
      required:
        - username
    SignUpRequest:
      properties:
        email:
          type: string
          format: email
          minLength: 6
          maxLength: 50
        username:
          type: string
          minLength: 2
          maxLength: 20
          example: demo
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 12
        confirmPassword:
          type: string
          format: password
      required:
        - email
        - username
        - password
        - confirmPassword
    SignUpResponse:
      type: object
