name: tests

on:
  schedule:
    - cron: "0 4 * * 0"  # At 04:00 on Sunday.
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [8, 11, 17]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
      - run: mvn -T1C clean verify
